Feat/alta usuario
Solify-IT/psyche-ing pull request #24
Opened 2021-04-29 03:04 UTC by scarlosro

### ALTA DE USUARIO

Se integra la funcionalidad para registrar un usuario, se realiza el pull request dado que la rama ya esta atrasada y corregir conflictos para evitar aun mas conflictos.

1. Ya se comunica front con back
2. Ya realiza verificaciones en front y back
3.  Falta implementar Test
4. Falta arreglar diseño
5. Una vez haciendo merge se realizará un refactor.

2021-04-29 19:05 UTC, albertcastaned requested changes
![image](https://user-images.githubusercontent.com/38927620/116604500-d3de1b80-a8f3-11eb-8c5b-b137aedc5b03.png)

Hace falta corregir el siguiente test por los nuevos cambios en el modelo de usuario. Fuera de eso lo veo bien. Solo hay que anotar esas pruebas automatizadas que faltan

2021-04-30 01:35 UTC, scarlosro commented
> ![image](https://user-images.githubusercontent.com/38927620/116604500-d3de1b80-a8f3-11eb-8c5b-b137aedc5b03.png)
> 
> Hace falta corregir el siguiente test por los nuevos cambios en el modelo de usuario. Fuera de eso lo veo bien. Solo hay que anotar esas pruebas automatizadas que faltan

Corregido, se hizo el ajuste necesario.

2021-04-30 02:35 UTC, albertcastaned commented
Aún hay algunos errores de compilación por los nuevos cambios traídos de develop. Si quieres probar si todo compila localmente puedes probar el comando `yarn typescript`. @scarlosro

2021-04-30 03:23 UTC, scarlosro commented
> Aún hay algunos errores de compilación por los nuevos cambios traídos de develop. Si quieres probar si todo compila localmente puedes probar el comando `yarn typescript`. @scarlosro

Listo, corregido.

2021-04-30 12:50 UTC, albertcastaned approved these changes
👍 💯

2021-04-30 12:50 UTC, merged