feat/ConsulltPatientList
Solify-IT/psyche-ing pull request #30
Opened 2021-05-06 19:43 UTC by arcosmarce

#### ¿Qué hace este PR?
Arreglo de defectos 12 y 13 del log de defectos de Soolers, haciendo la consulta desde el enlace de server y mapeando dinámicamente las opciones en los RadioButtons de los filtros

#### ¿Cómo debería ser probado manualmente?
Correr el back y front y checar si todos los pacientes son consultados en la tabla y si los filtros de RadioButton filtran correctamente de acurdo al tipo de paciente

#### ¿Algún background que desees proveer? 
Ninguno, es una consulta simple

#### ¿Cuáles son los tickets relevantes? 

Usa el formato: SIGLAS-XX (ejemplo SNLX-99)

#### Screenshots

#### Preguntas

#### Checklist

**Assignees:**
- [ x] Añadí la documentación necesaria, si es necesario. 
- [ x ] Agregué tests para probar que mi código funciona
- [ ] Revisé PRs existentes antes de publicar el mío. 

**Reviewers:**
- [ ] La Inyección de dependencias es correcta.
- [ ] No se importan archivos de niveles superiores de la arquitectura. 
- [ ] Los nombres de variables, objetos, clases y demás son entendibles. 
- [ ] El CI/CD Pipeline pasa.

2021-05-06 21:57 UTC, albertcastaned requested changes
Bien amiga solo recomendaría hacer los cambios que puse y ya podriamos pasarlo a develop. Si quieres esto hacerlo mañana no te preocupes por el demo. También hay que llenar la información de la descripción del pull request cuando son necesarios y si no borrarlos.

2021-05-06 21:57 UTC, albertcastaned commented on frontend/src/views/consultPatient.tsx
> +    const getPatients = async () => {
Como estándar hay que hacer todas las llamadas del endpoint en la capa/carpeta de api. Solo sería mover esto aquí para que en algún punto se pueda reutilizar la misma función si es necesario. Esto se definirá mejor ya que tengamos la guia del estandar de codificacion de frontend.

2021-05-06 21:57 UTC, albertcastaned commented on frontend/src/interfaces/options.js
> +export const todos = [
Hay que usar nombres más descriptivos y en inglés para seguir las recomendaciones del checklist. Este arreglo puedes hacer que una combinación de las anteriores haciendo como:

```
export const todos = [
optionsAsesoria ,
optionsClinica,
...
]
```

2021-05-06 22:00 UTC, arcosmarce commented on frontend/src/interfaces/options.js
> +export const todos = [
Correcto, esto se me pasó borrarlo pero no va

2021-05-06 22:00 UTC, arcosmarce commented on frontend/src/views/consultPatient.tsx
> +    const getPatients = async () => {
Súper! eso es lo que haremos Ricardo y yo mañana!

2021-05-08 03:45 UTC, arcosmarce commented on frontend/src/interfaces/options.js
> +export const todos = [
resuelto

2021-05-08 16:49 UTC, albertcastaned commented on frontend/src/interfaces/options.js
> +export const todos = [
Sigue teniendo el mismo detalle de estar repitiendo info cuando se podrían unir los arreglos. Intentaste con lo siguiente?
```
export const todos = {
  optionsAsesoria,
  optionsClinica,
  optionsPsicologia,
  optionsPsiquiatria,
};

```

2021-05-10 07:24 UTC, arcosmarce commented
Listo!

2021-05-10 16:36 UTC, albertcastaned approved these changes
👍

2021-05-10 16:36 UTC, merged