Refactor/register user
Solify-IT/psyche-ing pull request #44
Opened 2021-05-19 03:44 UTC by scarlosro

¿Qué hace esté PR?

1. Se corrige defectos, por lo cual se añade: Encriptación de contraseñas
2. Se añade el método al iniciar sesión
3. Se verifica que la contraseña coincida al momento.

¿Cómo debería ser probado manualmente?
Ingresar a http://localhost:3000/#/registerUser

¿Algún background que desees proveer?

1. Falta añadir la validación correcta en el front del username y correo para que muestre el error de manera explicita.
2. Hay que correr el comando yarn Install para instalar las nuevas dependencias (bcrypt)
3. Hay un fix del diseño que se implemento después de que yo hiciera esta rama, por lo cual, el diseño no coincide pero al hacer el merge se corrige.

<img width="1440" alt="Captura de Pantalla 2021-05-18 a la(s) 22 35 05" src="https://user-images.githubusercontent.com/33816613/118752758-4e31f980-b829-11eb-9c4d-a57d3208f2f0.png">

**Assignees:**
- [ X] Añadí la documentación necesaria, si es necesario. 
- [ ] Agregué tests para probar que mi código funciona
- [ ] Revisé PRs existentes antes de publicar el mío. 

**Reviewers:**
- [ ] La Inyección de dependencias es correcta.
- [ ] No se importan archivos de niveles superiores de la arquitectura. 
- [ ] Los nombres de variables, objetos, clases y demás son entendibles. 
- [ ] El CI/CD Pipeline pasa.

2021-05-19 03:53 UTC, albertcastaned requested changes
Arreglar merge conflicts y verificar la funcionalidad localmente. Los cambios en develop son
#42

2021-05-19 16:12 UTC, scarlosro commented
> Arreglar merge conflicts y verificar la funcionalidad localmente. Los cambios en develop son
> #42

Ya corregí los conflictos, en la tarde realizaré la revisión local y en caso de estar todo bien, solicito la revisión nuevamente.

2021-05-19 22:51 UTC, albertcastaned requested changes
La autenticación con JWT está desactivada en backend (backend/index.ts) ya que las lineas estan comentadas. Cómo probaste que funcionaba si estaba desactivado?

2021-05-20 04:27 UTC, albertcastaned requested changes

2021-05-20 04:27 UTC, albertcastaned commented on backend/src/infraestructure/datastore/datastore.ts
> +  }
Datastore debe ser general y no atado a una entidad específica como User. Podrías lograr lo mismo con el findOne que ya está definido.

2021-05-20 04:27 UTC, albertcastaned commented on backend/src/interface/repository/datastore.ts
> +  exists(username: string): Promise<Boolean>;
Lo mismo del datastore

2021-05-20 04:27 UTC, albertcastaned commented on backend/src/interface/repository/userRepository.ts
>      );
Para respetar eslint podria cambiar a:
```

const password = await bcrypt.hash(user.password, 8);  
const [result, error] = await wrapError(this.datastore.save<User>('User', { ...user, password } ),);


```

2021-05-20 04:27 UTC, albertcastaned commented on backend/src/interface/repository/userRepository.ts
> +      }
Respeta las pruebas unitarias que ya existen.

2021-05-20 04:27 UTC, albertcastaned commented on backend/src/interface/repository/userRepository.ts
> +      const matchpassword = await bcrypt.compare(password, user.password);
No sigue el PascalCase del estándar de código.

2021-05-20 04:27 UTC, albertcastaned commented on backend/src/test/repository/login.test.ts
> +    expect(result.password).toEqual('prueba12');
Encontrar manera de probar con unit tests que la contraseñas son encriptadas y desencriptadas exitosamente. Es una de las funciones más importantes del sistema.

2021-05-20 04:27 UTC, albertcastaned commented on frontend/src/views/Users/registerUser.tsx
>        CreateUser(newUser).then((response:any) => {
Pascal case

2021-05-20 12:39 UTC, albertcastaned approved these changes
Probado localmente. Se encripta el nuevo usuario y el login funciona 👍

2021-05-20 12:39 UTC, merged