feat: change password
Solify-IT/psyche-ing pull request #48
Opened 2021-05-20 18:14 UTC by albertcastaned

#### ¿Qué hace este PR?
Agrega la funcionalidad para cambiar la contraseña del usuario actual validando que sea segura y fuerte. Agrega un script para encriptar un string por si es necesario convertir una contraseña desencriptada a una encriptada.

#### ¿Cómo debería ser probado manualmente?
Ir a la /changePassword en frontend y llenar los campos. Una vez cambiado la contraseña cerrar sesión e iniciar sesión.

#### ¿Algún background que desees proveer? 

#### ¿Cuáles son los tickets relevantes? 
SOOL-576

#### Screenshots
![image](https://user-images.githubusercontent.com/38927620/119028552-32d00700-b96d-11eb-80d7-9c1672465bf9.png)
![image](https://user-images.githubusercontent.com/38927620/119028579-3c596f00-b96d-11eb-9b7e-f8615a4ef11d.png)

#### Checklist

**Assignees:**
- [x] Añadí la documentación necesaria, si es necesario. 
- [x] Agregué tests para probar que mi código funciona
- [x] Revisé PRs existentes antes de publicar el mío. 

**Reviewers:**
- [ ] La Inyección de dependencias es correcta.
- [ ] No se importan archivos de niveles superiores de la arquitectura. 
- [ ] Los nombres de variables, objetos, clases y demás son entendibles. 
- [ ] El CI/CD Pipeline pasa.

2021-05-21 03:07 UTC, scarlosro commented on frontend/src/views/Users/changePassword.tsx
> +        history.push(`/patient-profile/${user.id}`);
Cuidado, no son pacientes, son usuarios.

2021-05-21 03:14 UTC, albertcastaned commented on frontend/src/views/Users/changePassword.tsx
> +        history.push(`/patient-profile/${user.id}`);
Si tienes razon 😃. Es un defecto inyectado desde la user story de consultar perfil. Aunque sea de usuario, la ruta y los nombres de esa vista se puso como de perfil del paciente. Ahorita esta registrado como el defecto #57 del defect log. Por mientras, nos tuvimos que adaptar al defecto.

2021-05-21 04:07 UTC, scarlosro commented on frontend/src/views/Users/changePassword.tsx
> +        history.push(`/patient-profile/${user.id}`);
Ok, entonces todo lo demás lo veo correcto.

2021-05-21 04:10 UTC, scarlosro requested changes
Solo cambiar donde te indico "Te queremos caro :D" son cambios que después se nos podrían pasar y dejarlos así.

2021-05-21 04:10 UTC, scarlosro commented on frontend/src/views/Patients/registerPatient.tsx
> +          <div>Te queremos Caro :D</div>
Ojo con este tipo de mensajes.

2021-05-21 04:21 UTC, albertcastaned commented on frontend/src/views/Patients/registerPatient.tsx
> +          <div>Te queremos Caro :D</div>
@AdrizPaola

2021-05-21 12:00 UTC, arcosmarce commented on backend/src/test/presenter/user.changePassword.test.ts
> +  test('Te amooo AC <3 :DDD', async () => {
Las mismas observaciones de los mensajes :)

2021-05-21 12:06 UTC, arcosmarce approved these changes
- [x] Arquitectura: 
    - [x] Se cumple con la regla de dependencias por capas establecidas en el manual de arquitectura.
    - [x] Patrones de diseño son utilizados apropiadamente.
- [x] Casos especiales y límites:
    - [x] El programa está protegido de overflows, underflows, y condiciones fuera de límites.
    - [x] Todos los "edge cases" o casos especiales son atendidos.
    - [x] Todas las condiciones "imposibles" son absolutamente imposibles.
- [x] Uso funcional:
    - [x] Todos los endpoints están documentados en código o en algún documento.
    - [x] Todas las implementaciones de abstracciones o interfaces están definidas.
- [x] Seguridad:
    - [x] Todas las rutas privadas requieren autenticación.
    - [x] El programa no revela información confidencial.
    - [x] Llaves secretas son guardadas en variables de entorno y no en código.
- [x] Nombres:
    - [x] Ningún nombre de variables, objetos, funciones, son una sola letra. Todos los nombres son claros y se explican solos.
    - [x] El default export debe tener el mismo nombre del archivo en el que se encuentra escrito.
- [x] Estándares de código:
    - [x] Todo el código debe estar en inglés con la única excepción de cadenas o información que sea visible por el socio formador.
    - [x] Se sigue el estándar [AirBnB](https://github.com/airbnb/javascript) y no existen errores de compilación por ESLint.
    - [x] Todo los archivos son de tipo TypeScript para mantener consistencia.
- [x] Manejo de errores:
    - [x] Cuando se llama una función asíncrona, siempre manejar un posible error.
    - [x] El backend regresa errores descriptivos y únicos.
    - [x] El frontend maneja y regresa retroalimentación al recibir errores de backend.
- [x] Estilo:
    - [x] El frontend reutiliza componentes ya existentes con el mismo fin para cumplir con DRY.
    - [x] Los estilos son extendidos de un estilo base/padre y se ajustan localmente en la vista si es necesario.
    - [x] Se sigue la [guía de estilo](https://www.figma.com/file/zJ4JZFwS6uLnLNujAnkDtp/Guia-de-estilo?node-id=0%3A1).
    - [x] El frontend muestra retroalimentacion de que se están cargando o subiendo datos durante una llamada asíncrona.
- [x] Ortografía:
    - [x] No existen errores ortográficos o gramaticales en las partes visibles por el socio formador.
- [x] Testing:
    - [x] Las pruebas de regresión pasan correctamente.
    - [x] Se tiene una cobertura de por lo menos 80% del código de la user story en pruebas automatizadas.

2021-05-23 14:20 UTC, scarlosro approved these changes

2021-05-23 19:31 UTC, merged