Feat/admin update profile
Solify-IT/psyche-ing pull request #57
Opened 2021-05-25 05:05 UTC by domerent97

#### ¿Qué hace este PR?
Como admin, puedes modificar la información de cualquier usuario.

#### ¿Cómo debería ser probado manualmente?
Al consultar los usuarios, dar clic en el botón de editar. Será enviado a la pantalla de editar usuario, en vista de administrador. Se cambian los campos deseados y enviar petición.

#### ¿Algún background que desees proveer? 
Ninguno

#### ¿Cuáles son los tickets relevantes? 

Como administrador deseo modificar la información de un usuario para corregir errores de registro y reasignar las preferencias, así como datos de contactos actualizadas.

#### Screenshots

<img width="1237" alt="Screen Shot 2021-05-25 at 0 04 28" src="https://user-images.githubusercontent.com/48339576/119442093-d4988080-bcec-11eb-8d0a-f83b303ec1d6.png">

#### Preguntas

#### Checklist

**Assignees:**
- [x ] Añadí la documentación necesaria, si es necesario. 
- [ ] Agregué tests para probar que mi código funciona
- [ x] Revisé PRs existentes antes de publicar el mío. 

**Reviewers:**
- [ ] La Inyección de dependencias es correcta.
- [ ] No se importan archivos de niveles superiores de la arquitectura. 
- [ ] Los nombres de variables, objetos, clases y demás son entendibles. 
- [ ] El CI/CD Pipeline pasa.

2021-05-25 12:24 UTC, albertcastaned commented
¿Termina la tarea de incluir información de los integrantes?

2021-05-25 14:41 UTC, domerent97 commented
> ¿Termina la tarea de incluir información de los integrantes?

¡Sí! Deja incluyo Screenshots de eso.

2021-05-25 17:38 UTC, albertcastaned requested changes
Creo que falta subir los cambios de backend.

2021-05-25 17:49 UTC, domerent97 commented
> Creo que falta subir los cambios de backend.

Se utilizó un endpoint existente para la consulta, por lo que no hubo cambios en el back, sólo front :)

2021-05-25 18:11 UTC, albertcastaned commented
> > Creo que falta subir los cambios de backend.
> 
> Se utilizó un endpoint existente para la consulta, por lo que no hubo cambios en el back, sólo front :)

Ah perfecto!

2021-05-25 18:12 UTC, albertcastaned commented
Checar y arreglar merge conflicts nuevos. Creo que es por la user story de desactivar usuario por Carlos

2021-05-26 23:18 UTC, domerent97 reviewed
Conflictos resueltos :)

2021-05-27 00:00 UTC, albertcastaned commented
Puedes corregir el error de compilación de frontend? Creo que es por alguna línea que se comió al resolver merge conflicts. 
![image](https://user-images.githubusercontent.com/38927620/119745827-928a4e80-be54-11eb-9479-276d16505021.png)

2021-05-27 02:27 UTC, albertcastaned approved these changes

2021-05-27 02:28 UTC, merged