Feat: PDF  de un formato
Solify-IT/psyche-ing pull request #71
Opened 2021-06-01 03:01 UTC by arcosmarce

#### ¿Qué hace este PR?
Arreglo de defectos 55, 56, 57 y 58

#### ¿Cómo debería ser probado manualmente?
Consultar un formato e imprimirlo siguiendo los botones: formato de impresión -> Imprimir

#### ¿Cuáles son los IDs de defectos que corrige este PR? (si aplica)
55, 56, 57, 58

#### Screenshots
![WhatsApp Image 2021-05-31 at 9 46 54 PM](https://user-images.githubusercontent.com/61209708/120260507-a9b5ab80-c25b-11eb-9a3d-63981be3168a.jpeg)

#### Checklist

**Assignees:**
- [x] Añadí la documentación necesaria, si es necesario.
- [ ] Agregué tests para probar que mi código funciona
- [x] Revisé PRs existentes antes de publicar el mío.
- [x] Agregue artefactos de analisis, diseño, codigo, y pruebas a la [matriz de trazabilidad](https://docs.google.com/spreadsheets/d/1d1Xoovni1NMP6kdRcVcF63uMi7vCh7L5i_9vEs-EmSg/edit?usp=sharing).
- [x] Agregue los tiempos y fechas reales en el [plan de valor ganado](https://docs.google.com/spreadsheets/d/1MVEE5b19y5CxzQJxFSf31RyKIn8mhyHfYt4_y15_M5A/edit?usp=sharing).
- [x] Agregue defectos encontrados en el [defect log](https://docs.google.com/spreadsheets/d/1MVEE5b19y5CxzQJxFSf31RyKIn8mhyHfYt4_y15_M5A/edit?usp=sharing).

**Reviewers:**
- [ ] La Inyección de dependencias es correcta.
- [ ] No se importan archivos de niveles superiores de la arquitectura. 
- [ ] Los nombres de variables, objetos, clases y demás son entendibles. 
- [ ] El CI/CD Pipeline pasa.

2021-06-01 03:12 UTC, scarlosro commented
Hay que corregir los conflictos.

2021-06-01 03:44 UTC, albertcastaned commented
Tendra alguien impresora para probar como se ve?

2021-06-01 12:52 UTC, arcosmarce commented
Yo, yo lo imprimo

2021-06-01 23:39 UTC, scarlosro requested changes
Atender comentarios

2021-06-01 23:39 UTC, scarlosro commented on backend/src/index.ts
> +// import jwtConfig from 'utils/jwtConfig';
Variables comentadas, hay que checar.

2021-06-01 23:39 UTC, scarlosro commented on backend/src/index.ts
> +  /* app.use(
Igual aquí

2021-06-02 01:00 UTC, scarlosro commented
@arcosmarce resolver conflicto

2021-06-02 01:30 UTC, arcosmarce commented
Lineas descomentadas y arreglo de conflictos, listo!

2021-06-02 01:31 UTC, scarlosro approved these changes
👍🏽

2021-06-02 02:12 UTC, merged